---------------------------------- PROFESORES (Las contraseñas son iguales que los NIFs)
INSERT INTO PROFESOR VALUES(nextval('public.seq_profesor'), '12345678A', 'Profesor', 'A', 'PrimerAula', 'Datos de ejemplo', false, 'cb6f3ba16a6ddc7ae4f79f410abcd4187de72f269908baad3b3849e415271cd2');
INSERT INTO PROFESOR VALUES(nextval('public.seq_profesor'), '12345678B', 'Profesor', 'B', 'PrimerAula', '', false, '3ed3e7945d884279d7b49ba204d259c772cc308ca2fef28d4147ab13d329d8aa');
INSERT INTO PROFESOR VALUES(nextval('public.seq_profesor'), '12345678C', 'Profesor', 'C', 'SegundaAula', '', false, '0e80a75612b83f062bc9d3730221737797a621630b86f4c34ad8f3ec361c31f0');

---------------------------------- AULAS
INSERT INTO AULA VALUES(nextval('public.seq_aula'), 'Aula1', '100', 'Datos de ejemplo');
INSERT INTO AULA VALUES(nextval('public.seq_aula'), 'Aula2', '2', '');
INSERT INTO AULA VALUES(nextval('public.seq_aula'), 'Aula3', '0', '');

---------------------------------- AULA_PROFESOR
INSERT INTO AULA_PROFESOR VALUES (1, 2);
INSERT INTO AULA_PROFESOR VALUES (1, 3);
INSERT INTO AULA_PROFESOR VALUES (2, 4);

---------------------------------- ALUMNOS
INSERT INTO ALUMNO VALUES (nextval('public.seq_alumno'), currval('public.seq_alumno'), '01-01-2019', 'Alumno', 'A', 'PrimerAula', '', '', '1');
INSERT INTO ALUMNO VALUES (nextval('public.seq_alumno'), currval('public.seq_alumno'), '01-01-2019', 'Alumno', 'B', 'PrimerAula', '', '', '1');
INSERT INTO ALUMNO VALUES (nextval('public.seq_alumno'), currval('public.seq_alumno'), '01-01-2019', 'Alumno', 'C', 'SegundoAula', '', '', '2');

---------------------------------- EVALUACION 1
INSERT INTO EVALUACION VALUES (nextval('public.seq_evaluacion'), '01-01-2019', 1);
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));








---------------------------------- EVALUCION 2
INSERT INTO EVALUACION VALUES (nextval('public.seq_evaluacion'), '31-01-2019', 1);
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion')); 
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));
INSERT INTO PUNTUACION VALUES (nextval('public.seq_puntuacion'), (currval('public.seq_puntuacion') % 5) + 1, (currval('public.seq_puntuacion') % 114) + 1, currval('public.seq_evaluacion'));




